CREATE DATABASE AMAZONMUSIC;
--creo la base de datos--

USE AMAZONMUSIC; --USO LA BASE DE DATOS SELECCIONADA--


CREATE TABLE Songs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150),
  artist VARCHAR(100),
  album VARCHAR(100),
  duration INT
);